- name: 'Initalizing task with variables'
  set_fact:
    b_version: "{{ semaphore_vars.task_details.incoming_version | int }}"
    component_path: "/opt/semaphore_data/builds/elastic-component-v{{ semaphore_vars.task_details.incoming_version }}"

- name: "Apply build on each cluster (?, TODO)"
  loop: "{{ elastic_hosts }}"
  loop_control:
    loop_var: curr_host
  vars:
    curr_elastic_host: "{{ curr_host }}"  
  include_tasks: "update/update_loop.yaml"