- name: 'Initalizing task with variables'
  set_fact:
    b_version: "{{ semaphore_vars.task_details.target_version | int }}"
    component_path: "/opt/semaphore_data/builds/elastic-component-v{{ semaphore_vars.task_details.target_version }}"


- name: Include update.yaml for each host
  include_tasks: update.yaml
  vars:
    curr_elastic_host: "{{ c_h }}"
  loop: "{{ elastic_hosts }}"
  loop_control:
    loop_var: c_h