- block:
  - name: 'Get cluster settings'
    ansible.builtin.find:
      paths: "{{ component_path }}/jsons/cluster_settings"
      patterns: '*.json'
    register: list

  - name: 'Apply all settings in loop'
    ansible.builtin.uri:
      url: "{{ curr_elastic_host }}/_cluster/settings"
      validate_certs: False
      src: "{{ item.path }}"
      body_format: json
      method: "PUT"

      user: "{{ elastic_user }}"
      password: "{{ elastic_password }}"
      force_basic_auth: True
    vars:
      curr_component: "{{ item.path | basename | splitext | first }}"
    
    register: result    
    ignore_errors: true
    loop: "{{ list.files }}"
