- name: 'Apply build on node'
  vars:
    tasks: 
      - update_components
      - update_index_templates
      - update_ilm
      - update_cluster_settings
      - update_index_mappings 
      - update_index_settings

  include_tasks: "update_generic.yaml"
  loop: "{{ tasks }}"
  loop_control:
    loop_var: curr_task