- name: 'Apply build on node'
  vars:
    tasks: 
      - create_indices
      - update_index_aliases

      - update_components
      - update_ilm
      - update_index_templates

      - update_index_settings
      - update_index_mappings

      - update_cluster_settings

  include_tasks: "update_generic.yaml"
  loop: "{{ tasks }}"
  loop_control:
    loop_var: curr_task