- block:
  - set_fact:
      is_rollback: false
  - include_tasks: "{{ curr_task }}.yaml"

  # Check status, rollback if bad

  - name: 'Check status and apply rollback if need'
    include_tasks: ../check_with_rollback.yaml