- block:
  - name: 'Get built index settings paths' # (dict(target, settings))
    ansible.builtin.find:
      paths: "{{ component_path }}/jsons/index_settings"
      patterns: '*.json'
    register: list

  - name: 'Get content of index settings'
    set_fact:
      ise_content: "{{ ise_content | default([]) + [ise_obj]}}"

    loop: "{{ list.files }}"
    loop_control:
      loop_var: curr_file
    vars:
      ise_obj: "{{ lookup('ansible.builtin.file', curr_file.path) | from_json }}"

  - name: 'Apply component in loop'
    ansible.builtin.uri:
      url: "{{ curr_elastic_host }}/{{ ise_target }}/_settings"
      validate_certs: False

      body: "{{ ise_data }}"
      body_format: json
      method: "PUT"

      user: "{{ elastic_user }}"
      password: "{{ elastic_password }}"
      force_basic_auth: True
  
    vars:
      ise_data: "{{ ise.settings | to_json }}"
      ise_target: "{{ ise.target }}"
    
    register: result
    ignore_errors: true

    loop: "{{ ise_content }}"
    loop_control:
      loop_var: ise