- block:
  - set_fact:
      is_rollback: false
  - include_tasks: "{{ curr_task }}.yaml"

  - name: "Check cluster's health status"
    include_tasks: "../check_health.yaml"

  - name: 'Check status and apply rollback if need'
    include_tasks: ../check_with_rollback.yaml